### ISSUE TITLE
Relationship creation disabled

### ISSUE THREAD

**Issue by jorge-tautz** [inner-loop/java-neo4j-ogm#1]
On GraphResulMapper.java inside the for loop that iterates the relationships, this block stop the rest from being executed:

```
//TODO: WTF is going on here?!
if (start != null) {
    continue;
}
```

Why?

**Comment by mangrish** [comment]
You can see from the comment it was a bit of a brain freeze!

The issue was to do with not wanting to create relationships for objects that are already in the identity map (as they could have been made dirty in the session). I've fixed it by added an extra local map that holds any objects that are added to the identity map for the first time. This is then used in the same block you pasted.

I've fixed this code in commit: 72fd5365a907580390e5f068a66e1157557a920b

I should mention that the code base isn't yet ready. I still have a few random things that need to be fixed/implemented.

**Comment by jorge-tautz** [comment]
I've been playing with the lib, and notice that block when loading some objects i just saved.

Looking forward to use your code in production! It's objective, no need for a thousand other libs.

If you need any help let me know!

**Comment by mangrish** [comment]
For sure!

If you have any time to test it out and raise any bugs that would be awesome. Ideas and push requests are also welcome :)
